export interface FichaTecnica {
  nombres: string
  apellidoPaterno: string
  apellidoMaterno: string
  numControl: string
  carrera: string
  domicilio: string
  campus: string
  sexo: string
  correoElectronico: string
  telefono: string
  fechaNacimiento: string
  estadoCivil: string
  celular1: string
  lugarNacimiento: string
  semestre: string
  fecha: string;
  enfermedadcronica: string
  nombreenfermedadcronica: [string];
  tomamedicamento: string
  nombremedicamento: [string];
  vivirtranscursoestudios: string
  usodedrogas: string
  nombreinstitucion: string
  promgralprep: string
  becamanutencion: string
  becatransporte: string
  becaalimentacion: string
  becanomencionada: string
  booksread: string
  gruposrepresentativosenpreparatoria: string
  nombregruposrepresentativosenpreparatoria: [string];
  pertenecegrupooclub: string
  nombrepertenecegrupooclub: [string];
  razonparaestudiar: string
  trabajasenlactualidad: string
  dependesdetuspadres: string
  mediotransporte: string
  tiempollegadacasaescuela: string
  discapacidadquepadece: string
  discapacidadpsicosocial: string
  diagnosticadoporunprofesional: [string];
  perteneciaaetnia: string
  nombreetnia: [string];
  viveconeingresos:any;
  uid: any;
  id: any;
  }
